#Ro'yhatlar davomi function_mehtods.py
"""
25.10.2025
Royxatlar bn ishlash.
mehtods(.sort())
function(sum(),min(),max(),sorted(),list(),)
Ro'yhatlardan nuxsa olish
Tuple()o'zgarmas ro'yhat

"""
# davlatlar=["Uzbekistan","Braziliya","Ispaniya","Vatikan","Qazaqistan","Turkiya"]
# mashinalar=list(("BMW","audi","tico","damas","Colbat","Gentra","Malibu"))
# sonlar=list((2,3,4,5,25,26))
# print(davlatlar)
# print(mashinalar)
# print(sonlar)
# mashinalar= sorted(("BMW","audi","tico","damas","Colbat","Gentra","Malibu"))
# print(mashinalar)
# sonlar=sorted((7,8,4,9,2,4,1,0,10,3))
# print(sonlar)
# sonlar.sort(reverse=True )
# print(sonlar)
# sonlar.sort(reverse=False )
# print(sonlar)
# sonlar1=list(range(0,200) )
# print(sonlar1)

# sonlar2=list(range(3,89,2) )
# print(sonlar2)
# sonlar3=list(range(-80,523,3) )
# print(sonlar3)
# print(len(sonlar3))
# sonlar4=[-90,-0,87,-98,0,-789,]
# print(max(sonlar4))
# print(min(sonlar4))
# print(sum(sonlar4))
# davlatlar=["Uzbekistan","Braziliya","Ispaniya","Vatikan","Qazaqistan","Turkiya"]
# country= davlatlar[:]
# print(country)
# print(davlatlar)
# country.insert(0,"Singapur")
# print(country)
# print(davlatlar)

lola=list(range(1,24,2))
print("Asl korinishi:",lola)
print("1 dan 7gacha:",lola[0:4])
print(lola[:])


